services:
  db:
    image: postgres:latest
    container_name: db
    ports:
      - "9432:5432"
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - db:/var/lib/postgresql/data

  keycloak_db:
    image: postgres:latest
    container_name: keycloak_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    volumes:
      - keycloak_db:/var/lib/postgresql/data

  keycloak:
    image: docker.io/bitnami/keycloak:latest
    ports:
      - "8888:8080"
    environment:
      KEYCLOAK_CREATE_ADMIN_USER: true
      KEYCLOAK_ADMIN_USER: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_DATABASE_HOST: keycloak_db
      KEYCLOAK_DATABASE_PORT: 5432
      KEYCLOAK_DATABASE_NAME: keycloak
      KEYCLOAK_DATABASE_USER: keycloak
      KEYCLOAK_DATABASE_PASSWORD: keycloak
    volumes:
      - ./keycloak/themes:/opt/bitnami/keycloak/themes/custom
    depends_on:
      - db

volumes:
  db:
  keycloak_db:
